name: GetManager
permissions:
  contents: write  # Allow writing to repository contents (for pushing tags)
  actions: read   # Allows triggering actions

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["oneplus_13T"]
    types: [completed]

jobs:
  get_ksu_manager:
    runs-on: ubuntu-latest
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: 安装依赖
        run: sudo apt update && sudo apt install -y git curl jq

      - name: 设定 KSU 环境变量
        run: |
          echo DATE=$(date +%F) >> $GITHUB_ENV
          
          echo "This is the SukiSU variant"
          git clone https://github.com/SukiSU-Ultra/SukiSU-Ultra.git
          cd SukiSU-Ultra
          KSU_GIT_VERSION=$(git rev-list --count HEAD)
          KSU_VERSION=$((10000 + KSU_GIT_VERSION + 700))
          echo $KSU_VERSION
          echo "KSU_VERSION=$KSU_VERSION" >> $GITHUB_ENV
          
      - name: 添加 KernelSU
        run: |
          
          echo "SukiSU..."
          REPO="SukiSU-Ultra/SukiSU-Ultra"
          FILENAME="build-manager.yml"

          # 获取最新成功构建的 ID
          BUILD_ID=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/$REPO/actions/workflows/$FILENAME/runs?status=success" | \
          jq -r '.workflow_runs[0].id')
          echo ＂BUILD_ID=$BUILD_ID＂
          # 获取该构建的 Artifacts
          ARTIFACTS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/$REPO/actions/runs/$BUILD_ID/artifacts")
          echo ＂ARTIFACTS=$ARTIFACTS＂
          # 获取 Manager 文件的下载链接
          
          
          DOWNLOAD_URL=$(echo "$ARTIFACTS" | jq -r '.artifacts[] | select(.name == "manager") | .archive_download_url')
          echo $DOWNLOAD_URL

          # 下载 Manager 文件
          curl -L -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -o "SukiSU-manager(${{ env.KSU_VERSION }}).zip" "$DOWNLOAD_URL"
          echo "Manager 文件已下载为：SukiSU-manager(${{ env.KSU_VERSION }}).zip"
          unzip *.zip
          mv *.apk SukiSU_${{ env.KSU_VERSION }}.apk
          
      - name: 上传编译资产
        uses: actions/upload-artifact@v4
        with:
          name: SukiSU-Manager(${{ env.KSU_VERSION }})
          path: |
            *.apk

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
         name: Release ${{ env.DATE }}
         body: 一加13T 一加平板2Pro SukiSU_${{ env.KSU_VERSION }}
         tag_name: ${{ env.KSU_VERSION }}
         files: ./*.apk
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
